SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{684C7937D70EBB46}" {
   m_Info SCR_UIInfo "{684C7937CE3F75B6}" {
    Name "506IRRU"
    Icon "{4D6CB4D087CE9A75}Images/506_Icon.edds"
   }
   m_Order 412905
   m_LabelType FACTION_506IRRU
   m_LabelGroupType FACTION
  }
 }
}