EntityPersistenceConfig {
 Rule PrefabPersistenceConfigRule "{64F09C88C714F0E9}" {
  Prefabs {
   "{C95E11C60810F432}Prefabs/Items/Core/Item_Base.et"
   "{5C848F741AE1CE15}Prefabs/Items/Core/ItemGameEntity_base.et"
   "{DFB0F41DA8D04752}Prefabs/Accessories/IRRU_Radio_ANPRC_JTAC_Right.et"
   "{F526F4C334526B74}Prefabs/Accessories/IRRU_Radio_ANPRC_LEFT_JTAC.et"
   "{3AAE94CE6ADC37E6}Prefabs/Accessories/IRRU_Radio_ANPRC_V3.et"
   "{ED6C531BB75E8DB5}Prefabs/Accessories/IRRU_Radio_MPU5.et"
   "{F1612C6EE78043DC}Prefabs/Pouches/GRS Compatability Layer/GRS_330D_Pouch.et"
   "{A19CBF330C6D2622}Prefabs/Pouches/GRS Compatability Layer/GRS_330D_Wide_Pouch.et"
   "{62F4B1B414B7161B}Prefabs/Pouches/GRS Compatability Layer/GRS_Angled_Pistol_Pouch.et"
   "{E25C664EEC5C2166}Prefabs/Pouches/GRS Compatability Layer/GRS_ARSingle_Pouch.et"
   "{941F0E153685A463}Prefabs/Pouches/GRS Compatability Layer/GRS_Belly_Pouch_V5.et"
   "{65A217F899903D1A}Prefabs/Pouches/GRS Compatability Layer/GRS_BFG_Trauma.et"
   "{FEC6E47E73D1F3A9}Prefabs/Pouches/GRS Compatability Layer/GRS_Blowout_TQS.et"
   "{FC35998CD73A3646}Prefabs/Pouches/GRS Compatability Layer/GRS_CAG_Dangler_1.et"
   "{9F93AEF86F6217FC}Prefabs/Pouches/GRS Compatability Layer/GRS_CryeGP6x6.et"
   "{535CCA5E07D6F526}Prefabs/Pouches/GRS Compatability Layer/GRS_Detcord_Pouch.et"
   "{E2B4D27EAB67EB2A}Prefabs/Pouches/GRS Compatability Layer/GRS_Dual_SingleM4_Pouch_Base.et"
   "{88B071D3F75B4193}Prefabs/Pouches/GRS Compatability Layer/GRS_Lunchbox_Folded.et"
   "{CDCB8710ADB5ED6F}Prefabs/Pouches/GRS Compatability Layer/GRS_M18_Filbe_Pouch.et"
   "{7FD7D805A6479629}Prefabs/Pouches/GRS Compatability Layer/GRS_M18_Filbe_Pouch_V2.et"
   "{762907B8B13C57E4}Prefabs/Pouches/GRS Compatability Layer/GRS_M67_Filbe_Pouch.et"
   "{F45D0E4120AE8462}Prefabs/Pouches/GRS Compatability Layer/GRS_Medkit_Tearoff.et"
   "{DBF1A34BC391CCAB}Prefabs/Pouches/GRS Compatability Layer/GRS_Pistol_Pouch.et"
   "{6A47A6EDF009D66F}Prefabs/Pouches/GRS Compatability Layer/GRS_Placard_ARC.et"
   "{2B83F5F718A7B91F}Prefabs/Pouches/GRS Compatability Layer/GRS_Placard_AVSKangaroo.et"
   "{DB2967818840BCA4}Prefabs/Pouches/GRS Compatability Layer/GRS_Placard_AVSM4Flap.et"
   "{24DFD55C6F097012}Prefabs/Pouches/GRS Compatability Layer/GRS_Placard_FerroDope.et"
   "{B6F10C4BD2DCAE05}Prefabs/Pouches/GRS Compatability Layer/GRS_Placard_KTAR.et"
   "{C4A01A46BF87F402}Prefabs/Pouches/GRS Compatability Layer/GRS_Placard_MKV.et"
   "{94BD3BB9A7607CE7}Prefabs/Pouches/GRS Compatability Layer/GRS_Radio_ANPRC_Pouch_V2.et"
   "{BCD99F95866F1FFD}Prefabs/Pouches/GRS Compatability Layer/GRS_Radio_MPU5_V2_Pouch.et"
   "{7C7F6D4083FAEA14}Prefabs/Pouches/GRS Compatability Layer/GRS_Side_Pouch_1.et"
   "{5FA80653EB0A8F87}Prefabs/Pouches/GRS Compatability Layer/GRS_SingleM4_Pouch_Base.et"
   "{3AD3B636574DEF63}Prefabs/Pouches/GRS Compatability Layer/GRS_SOFLCS_AR_Pouch.et"
   "{BF7EACBAECCA1654}Prefabs/Pouches/GRS Compatability Layer/GRS_SOFLCS_Dual_AR_Pouch.et"
   "{D50EDC9BB84DD48A}Prefabs/Pouches/GRS Compatability Layer/GRS_Spiritus_CCS.et"
   "{53925A30691D584A}Prefabs/Pouches/GRS Compatability Layer/GRS_SPS556_Pouch.et"
   "{D7069AE2299692E2}Prefabs/Pouches/GRS Compatability Layer/TKO_Pouch_TQ.et"
   "{A00A86C2FEB414A3}Prefabs/Pouches/GRS Compatability Layer/TKO_Pouch_Multitool.et"
   "{2134E5F5A56F94CC}Prefabs/Backpanels/Accessories/506_JTAC_Antenna.et"
  }
 }
}