SCR_AvailableActionsDisplay : "{80CC0413DDBDFCB9}Configs/ControlHints/AvailableActions.conf" {
 m_aActions {
  SCR_AvailableActionContext "{673700B79154225B}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{673700B6770AA695}" {
    }
   }
   m_sTag "IRRU_VON"
   m_sAction "IRRU_SetFrequencyAction"
   m_sName "Set Frequency Manually"
  }
  SCR_AvailableActionContext "{67451B0100000005}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{67451B0100000006}" {
    }
   }
   m_sTag "IRRU_VON"
   m_sAction "IRRU_VONRoutingAction"
   m_sName "Change Ear Routing"
  }
  SCR_AvailableActionContext "{67451B0100000007}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{67451B0100000008}" {
    }
   }
   m_sTag "IRRU_VON"
   m_sAction "IRRU_VONBeepTypeAction"
   m_sName "Change Beep Sound"
  }
  SCR_AvailableActionContext "{67451B0100000009}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{67451B010000000A}" {
    }
   }
   m_sTag "IRRU_VON"
   m_sAction "IRRU_VolumeAction"
   m_sName "Change Channel Volume"
  }
  SCR_AvailableActionContext "{67451B0100000001}" {
   m_aConditions {
    SCR_VONMenuActiveActionCondition "{67451B0100000002}" {
    }
   }
   m_sTag "IRRU_VON"
   m_sAction "IRRU_AlternateChannelAction"
   m_sName "Set Alternate Channel"
  }
  SCR_AvailableActionContext "{67451B0100000003}" {
   m_aConditions {
    SCR_IsContextEnabledCondition "{673700BE9B8929DF}" {
    }
   }
   m_sTag "IRRU_VON"
   m_sAction "IRRU_AlternateChannel"
   m_sName "Transmit Alternate"
  }
 }
}