SCR_MilitarySupplyAllocationConfig {
 m_aMilitarySupplyAllocationRankList {
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA1}" {
   m_iMilitarySupplyAllocationValue 500
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA5}" {
   m_iMilitarySupplyAllocationValue 700
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA6}" {
   m_iMilitarySupplyAllocationValue 900
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA7}" {
   m_iMilitarySupplyAllocationValue 1100
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA8}" {
   m_iMilitarySupplyAllocationValue 1300
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA9}" {
   m_iMilitarySupplyAllocationValue 1500
  }
 }
}