EditablePrefabsConfig {
 m_Settings {
  EditablePrefabsSetting "{684D74BE57384C61}" {
   m_Target "{19C829C731AEE785}Prefabs/Characters/Core/506IRRU"
  }
  EditablePrefabsSetting "{684D74BE45BB950C}" {
   m_Target "{96B8D3215A81A750}Prefabs/AI/Groups/506IRRU"
  }
 }
}