SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{685E695B987FB48E}" {
   m_sEntityPrefab "{D636767A555794F7}Prefabs/Characters/Loadout_Menu.et"
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{685E695BEEE3958E}" {
     m_eSlotTypes GROUP_SMALL
    }
    SCR_EntityCatalogEditorData "{685E695BEDE9B6BC}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{685E695B9FCD4C61}" {
   m_sEntityPrefab "{E36A0AB6F35F91AC}Prefabs/Characters/Loadout_Presets.et"
   m_aEntityDataList {
    SCR_EntityCatalogSpawnerData "{685E695BE234619F}" {
     m_eSlotTypes GROUP_SMALL
    }
    SCR_EntityCatalogEditorData "{685E695BE5022528}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{685E695B9E95479E}" {
   m_sEntityPrefab "{1975B045BDF1C0C3}Prefabs/Characters/Loadout_Share.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{685E695BF7778740}" {
    }
    SCR_EntityCatalogSpawnerData "{685E695BF5718CE7}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{6860764952FB759C}" {
   m_sEntityPrefab "{587E9D0970574C39}Prefabs/Characters/Loadout_Dev.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{686076495E08833C}" {
    }
    SCR_EntityCatalogSpawnerData "{686076494623744B}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{685C873299BE2FD2}" {
   m_sIdentifier "Campaign"
   m_aEntities {
    SCR_EntityCatalogEntry "{685C87328939788E}" {
     m_sEntityPrefab "{967835C05D83CBF1}Prefabs/Characters/LoadoutAI.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{685C8732E2E78772}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{685C8732E685E747}" {
       m_eRequiredRank GENERAL
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{685C873299BCAC9B}" {
   m_sIdentifier "Variants"
  }
 }
}