SCR_MissionHeader {
 World "{81F72875C4B4B2FF}worlds/Test2.ent"
 m_sName "<Insert world name>"
 m_sAuthor "<Insert your name>"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}