AudioVariablesClass {
 Variables {
  AudioVariableClass EarRouting {
   source External
   value_max 2
  }
  AudioVariableClass JamStrength {
   source External
   value 1
  }
  AudioVariableClass ChannelVolume {
   source External
   value 1
  }
  AudioVariableClass SignalQuality {
   source External
   value 1
  }
 }
}