blank_issues_enabled: false
contact_links:
  - name: Ask a Question or Get Help
    url: https://github.com/506IRRUS-4LogisticsTeam/506IRRU-S4-Mod-Team/discussions
    about: Please use GitHub Discussions or Discord for general inquiries.
