SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{668D15F6D6B20CDF}" {
     m_sEntityPrefab "{02B05D6A62F69E2D}H1.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668D15F6D8717448}" {
       m_eItemType HEADWEAR
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{668D15F6D76A8C4B}" {
     m_sEntityPrefab "{F4AE06BB2D8AAD20}H2.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668D15F6DB76784C}" {
       m_eItemType HEADWEAR
      }
     }
    }
   }
  }
 }
}