SCR_MissionHeader {
 World "{C571B56AA26CE909}Worlds/CACTF/CACTF_v1.0.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "506IRRU CACTF "
 m_sAuthor "S-3 Training/S-4 Missions"
 m_sDescription "OSUT Template made by SSG Clements and 1LT C. Mitchell"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}