ActionManager {
 Contexts {
  ActionContext CharacterWeaponContext {
   Actions {
    Action LBT_RHS_LightDeviceCADec {
     Type AnalogRelative
     InputSource InputSourceSum "{64517EE2D0D1802C}" {
      FilterPreset "click"
      Sources {
       InputSourceValue "{64517EE2D0D18034}" {
        FilterPreset "click"
        Input "keyboard:KC_COMMA"
        Filter InputFilterRepeat "{64517EE5F8EE0AAA}" {
        }
       }
       InputSourceCombo "{64517EE2D0D18003}" {
        FilterPreset "gamepad:RHS_LightDeviceToggle"
        Sources {
         InputSourceValue "{64517EE2D0D18002}" {
          FilterPreset "gamepad:RHS_LightDeviceToggle"
          Input "gamepad0:y"
          Filter InputFilterHold "{64517EE2D0D18001}" {
           HoldDuration 200
          }
         }
         InputSourceValue "{64517EE2D0D18000}" {
          FilterPreset "gamepad:RHS_LightDeviceToggle"
          Input "gamepad0:pad_up"
          Filter InputFilterDoubleClick "{64517EE2D0D18006}" {
          }
         }
        }
       }
      }
     }
    }
    Action LBT_RHS_LightDeviceCAInc {
     Type AnalogRelative
     InputSource InputSourceSum "{64517EE406B2B4BB}" {
      FilterPreset "click"
      Sources {
       InputSourceValue "{64517EE406B2B4BE}" {
        FilterPreset "click"
        Input "keyboard:KC_PERIOD"
        Filter InputFilterRepeat "{64517EE406B2B483}" {
        }
       }
       InputSourceCombo "{64517EE406B2B481}" {
        FilterPreset "gamepad:RHS_LightDeviceToggle"
        Sources {
         InputSourceValue "{64517EE406B2B480}" {
          FilterPreset "gamepad:RHS_LightDeviceToggle"
          Input "gamepad0:y"
          Filter InputFilterHold "{64517EE406B2B486}" {
           HoldDuration 200
          }
         }
         InputSourceValue "{64517EE406B2B484}" {
          FilterPreset "gamepad:RHS_LightDeviceToggle"
          Input "gamepad0:pad_down"
          Filter InputFilterDoubleClick "{64517EE406B2B48B}" {
          }
         }
        }
       }
      }
     }
    }
    Action RHS_LightDeviceToggleSA {
     InputSource InputSourceSum "{632408409503647A}" {
      FilterPreset "click"
      Sources {
       InputSourceValue "{6324084095036447}" {
        FilterPreset "click"
        Input "keyboard:KC_COLON"
        Filter InputFilterSingleClick "{632408409503644A}" {
         ClickDuration 250
        }
       }
       InputSourceCombo "{632408409503644F}" {
        FilterPreset "gamepad:RHS_LightDeviceToggle"
        Sources {
         InputSourceValue "{632408409503644E}" {
          FilterPreset "gamepad:RHS_LightDeviceToggle"
          Input "gamepad0:y"
          Filter InputFilterHold "{6324084095036453}" {
           HoldDuration 200
          }
         }
         InputSourceValue "{6324084095036452}" {
          FilterPreset "gamepad:RHS_LightDeviceToggle"
          Input "gamepad0:pad_left"
          Filter InputFilterDoubleClick "{6324084095036451}" {
          }
         }
        }
       }
      }
     }
    }
    Action RHS_LightDeviceHoldSA {
     InputSource InputSourceSum "{6324084199FD7838}" {
      FilterPreset "hold"
      Sources {
       InputSourceValue "{6324084199FD7801}" {
        FilterPreset "hold"
        Input "keyboard:KC_COLON"
        Filter InputFilterHold "{6324084199FD7806}" {
         Multiplier 2
         HoldDuration 250
        }
       }
       InputSourceCombo "{6324084199FD780A}" {
        FilterPreset "gamepad:RHS_LightDeviceHold"
        Sources {
         InputSourceValue "{6324084199FD7809}" {
          FilterPreset "gamepad:RHS_LightDeviceHold"
          Input "gamepad0:pad_left"
          Filter InputFilterHold "{6324084199FD7808}" {
           Multiplier 2
           HoldDuration 1000
          }
         }
        }
       }
      }
     }
    }
   }
  }
 }
}