SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{5DCAC7CD71C14FD8}" {
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{63240842A48D6FD8}" {
     m_sActionName "RHS_LightDeviceToggleSA"
     m_sDisplayName "Standalone Weapon Light Toggle"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{6324084312A62035}" {
     m_sActionName "RHS_LightDeviceHoldSA"
     m_sDisplayName "Standalone Weapon Light Momentary"
     m_sPreset "hold"
    }
    SCR_KeyBindingEntry "{64517EE0CF4B3626}" {
     m_sActionName "LBT_RHS_LightDeviceCADec"
     m_sDisplayName "Light Device Increase Focus"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{64517EE0CF4003C8}" {
     m_sActionName "LBT_RHS_LightDeviceCAInc"
     m_sDisplayName "Light Device Decrease Focus"
     m_sPreset "click"
    }
   }
  }
 }
}