ActionManager {
 Contexts {
  ActionContext MapContext {
   Actions {
    Action MapMortarAim {
     InputSource InputSourceSum "{666D407488372AD1}" {
      Sources {
       InputSourceValue "{666D40748C36880C}" {
        Input "keyboard:KC_T"
        Filter InputFilterDown "{666D40749A27398D}" {
        }
       }
      }
     }
    }
    Action MapMortarCharge {
     InputSource InputSourceSum "{666D407488372AD2}" {
      Sources {
       InputSourceValue "{666D40748C36880D}" {
        Input "keyboard:KC_C"
        Filter InputFilterDown "{666D40749A27398E}" {
        }
       }
      }
     }
    }
   }
  }
 }
}