IRRU_AnimationHelpersConfig {
 m_aEntries {
  IRRU_AnimationHelperConfigEntry "{66263A6576EEFF0A}" {
   m_eID CPR
   m_sPrefabName "{604E93B236B19A2A}Prefabs/Helpers/IRRU_Medical_CPRHelperCompartment.et"
  }
 }
}