SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{64B058B2A4EE8C6E}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{64B058B251340A0B}" {
     m_sEntityPrefab "{1526E12F183D980E}Prefabs/Weapons/Mk48.et"
    }
    SCR_EntityCatalogInventoryItem "{64B058B20519F91F}" {
     m_sEntityPrefab "{D6D1BD6676214AAD}Prefabs/Weapon_Parts/Box_762x51_MK48_100rnd_4Ball_1Tracer.et"
    }
   }
  }
 }
}