ActionManager {
 Contexts {
  ActionContext MapContext {
   Actions {
    Action MapMortarAim {
     InputSource InputSourceSum "{666D407488372AD1}" {
      Sources {
       InputSourceValue "{666D40748C36880C}" {
        Input "keyboard:KC_T"
        Filter InputFilterDown "{666D40749A27398D}" {
        }
       }
       InputSourceValue "{666E3618120DE7C9}" {
        Input "gamepad0:thumb_left"
        Filter InputFilterDown "{666E361815AF2053}" {
        }
       }
      }
     }
    }
    Action MapMortarCharge {
     InputSource InputSourceSum "{666D407488372AD2}" {
      Sources {
       InputSourceValue "{666D40748C36880D}" {
        Input "keyboard:KC_C"
        Filter InputFilterDown "{666D40749A27398E}" {
        }
       }
       InputSourceValue "{666E361808E2048A}" {
        Input "gamepad0:shoulder_right"
        Filter InputFilterDown "{666E36180DA2911B}" {
        }
       }
      }
     }
    }
    Action MapMortarExit {
     InputSource InputSourceSum "{666D407488372AD3}" {
      Sources {
       InputSourceValue "{666D40748C36880E}" {
        Input "keyboard:KC_ESCAPE"
        Filter InputFilterDown "{666D40749A27398F}" {
        }
       }
       InputSourceValue "{666E3618720C1D6D}" {
        Input "gamepad0:b"
        Filter InputFilterDown "{666E3618759A506B}" {
        }
       }
       InputSourceValue "{666E361853355D9F}" {
        Input "keyboard:KC_X"
        Filter InputFilterDown "{666E361839CC0994}" {
        }
       }
      }
     }
    }
   }
  }
 }
}