SCR_MissionHeader {
 World "{B11471C6624C5FE7}worlds/AresTest/AresTest.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "AresTest"
 m_sAuthor "<Insert your name>"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}