SCR_PlaceableEntitiesRegistry {
 m_sAddon "ArmaReforger"
 m_sSourceDirectory "{5307E2851958D16D}Prefabs/Characters/Factions/BLUFOR"
 m_bExposed 1
 m_Prefabs {
  "{D636767A555794F7}Prefabs/Characters/Loadout_Menu.et"
  "{E36A0AB6F35F91AC}Prefabs/Characters/Loadout_Presets.et"
  "{1975B045BDF1C0C3}Prefabs/Characters/Loadout_Share.et"
  "{587E9D0970574C39}Prefabs/Characters/Loadout_Dev.et"
 }
}