SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{667D547B87E228BD}" {
   m_Info SCR_UIInfo "{667D547B87E22B9F}" {
    Name "506IRRU"
    Icon "{4D6CB4D087CE9A75}Images/506_Icon.edds"
   }
   m_LabelType FACTION_506IRRU
   m_LabelGroupType FACTION
  }
 }
}