SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EEB3F124F9}" {
   m_aMultiLists {
    SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
     m_aEntities {
      SCR_EntityCatalogInventoryItem "{6590F7D1AAFBF3FE}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F03A9BEAB6738C}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F49623ED78AD81}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogInventoryItem "{65F49623E423424B}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogEntry "{65EB5734BFF7DABF}" {
       m_bEnabled 0
      }
      SCR_EntityCatalogEntry "{65EB5734BF07478B}" {
       m_bEnabled 0
      }
     }
    }
   }
  }
 }
}