SCR_MissionHeader {
 World "{AED91616DB396DCA}Worlds/Operation_Frostline/OFL_Base_Template/506th_OFL_Base_Template.ent"
 m_sName "Operation Frostline - Testing Template"
 m_sAuthor "506IRRU S-4 Logistics"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_bMapMarkerEnableDeleteByAnyone 1
 m_iMapMarkerLimitPerPlayer 100
}