SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6134C3321AC153FC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{692642D98CF22992}" {
     m_sEntityPrefab "{0ADE4EB034FA0206}Prefabs/Items/PersonalBelongings/IRRU_PersonalBelongings_US.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{692642D994F9E063}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
      SCR_EntityCatalogIdentityItemData "{692642D863E50AF5}" {
      }
     }
    }
   }
  }
 }
}