ActionManager {
 Contexts {
  ActionContext VONContext {
   Actions {
    Action IRRU_AlternateChannel {
     InputSource InputSourceSum "{673700B4AADC3C39}" {
      Sources {
       InputSourceValue "{673700B4AB103252}" {
        FilterPreset "hold"
        Input "keyboard:KC_Y"
       }
       InputSourceCombo "{6737008800000003}" {
        Sources {
         InputSourceValue "{6737008800000004}" {
          Input "gamepad0:shoulder_left"
          Filter InputFilterPressed "{6737008800000005}" {
          }
         }
         InputSourceValue "{6737008800000006}" {
          Input "gamepad0:shoulder_right"
          Filter InputFilterPressed "{6737008800000007}" {
          }
         }
        }
       }
      }
     }
    }
   }
  }
  ActionContext VONMenuContext {
   Actions {
    Action IRRU_VONRoutingAction {
     InputSource InputSourceSum "{672D212294838480}" {
      Sources {
       InputSourceValue "{672D21236781B911}" {
        FilterPreset "click"
        Input "keyboard:KC_T"
        Filter InputFilterDown "{672D21233374744D}" {
        }
       }
       InputSourceValue "{672D21236425479D}" {
        FilterPreset "gamepad:click"
        Input "gamepad0:shoulder_right"
        Filter InputFilterDown "{672D212331695378}" {
        }
       }
      }
     }
    }
    Action IRRU_SetFrequencyAction {
     InputSource InputSourceSum "{672D212F156958F0}" {
      Sources {
       InputSourceValue "{672D212FEB4F92DF}" {
        FilterPreset "click"
        Input "keyboard:KC_F"
        Filter InputFilterDown "{672D212FE2D6204D}" {
        }
       }
       InputSourceValue "{672F61C8AA229BC6}" {
        FilterPreset "click"
        Input "gamepad0:shoulder_left"
        Filter InputFilterDown "{672F61C8A2BCDD4C}" {
        }
       }
      }
     }
    }
    Action IRRU_VONBeepTypeAction {
     InputSource InputSourceSum "{672F61C86E36F488}" {
      Sources {
       InputSourceValue "{672F61C86C493BA4}" {
        FilterPreset "click"
        Input "keyboard:KC_K"
        Filter InputFilterDown "{672F61C837F10054}" {
        }
       }
       InputSourceValue "{672F61C80F375AA7}" {
        FilterPreset "click"
        Input "gamepad0:y"
        Filter InputFilterDown "{672F61C938751766}" {
        }
       }
      }
     }
    }
    Action IRRU_VolumeAction {
     Type AnalogRelative
     InputSource InputSourceSum "{673167EABBED50EE}" {
      Sources {
       InputSourceCombo "{673167EABDC74C97}" {
        Sources {
         InputSourceValue "{673167EAB4947EF9}" {
          Input "keyboard:KC_LCONTROL"
          Filter InputFilterPressed "{673167EE0A22EB9B}" {
          }
         }
         InputSourceValue "{673167EB5D148B11}" {
          Input "mouse:wheel"
          Filter InputFilterValue "{673167EB2E9E8FAB}" {
          }
         }
        }
       }
      }
     }
    }
    Action IRRU_AlternateChannelAction {
     InputSource InputSourceSum "{67451A0100000001}" {
      Sources {
       InputSourceCombo "{67451A0100000004}" {
        Sources {
         InputSourceValue "{67451A0100000005}" {
          Input "keyboard:KC_LCONTROL"
         }
         InputSourceValue "{67451A0100000002}" {
          Input "keyboard:KC_F"
          Filter InputFilterDown "{6737008829E8239A}" {
          }
         }
        }
       }
       InputSourceCombo "{6737008800000001}" {
        Sources {
         InputSourceValue "{6737008800000008}" {
          Input "gamepad0:shoulder_left"
          Filter InputFilterPressed "{6737008800000009}" {
          }
         }
         InputSourceValue "{673700880000000A}" {
          Input "gamepad0:x"
          Filter InputFilterDown "{673700880000000B}" {
          }
         }
        }
       }
      }
     }
    }
   }
  }
 }
}