ActionManager {
 Contexts {
  ActionContext VONMenuContext {
   Actions {
    Action IRRU_VONRoutingAction {
     InputSource InputSourceSum "{672D212294838480}" {
      Sources {
       InputSourceValue "{672D21236781B911}" {
        FilterPreset "click"
        Input "keyboard:KC_T"
        Filter InputFilterDown "{672D21233374744D}" {
        }
       }
       InputSourceValue "{672D21236425479D}" {
        FilterPreset "gamepad:click"
        Input "gamepad0:shoulder_right"
        Filter InputFilterDown "{672D212331695378}" {
        }
       }
      }
     }
    }
   }
  }
 }
}