ActionManager {
 Contexts {
  ActionContext VONMenuContext {
   Actions {
    Action IRRU_VONRoutingAction {
     InputSource InputSourceSum "{672D212294838480}" {
      Sources {
       InputSourceValue "{672D21236781B911}" {
        FilterPreset "click"
        Input "keyboard:KC_T"
        Filter InputFilterDown "{672D21233374744D}" {
        }
       }
       InputSourceValue "{672D21236425479D}" {
        FilterPreset "gamepad:click"
        Input "gamepad0:shoulder_right"
        Filter InputFilterDown "{672D212331695378}" {
        }
       }
      }
     }
    }
    Action IRRU_SetFrequencyAction {
     InputSource InputSourceSum "{672D212F156958F0}" {
      Sources {
       InputSourceValue "{672D212FEB4F92DF}" {
        FilterPreset "click"
        Input "keyboard:KC_F"
        Filter InputFilterDown "{672D212FE2D6204D}" {
        }
       }
       InputSourceValue "{672F61C8AA229BC6}" {
        FilterPreset "click"
        Input "gamepad0:shoulder_left"
        Filter InputFilterDown "{672F61C8A2BCDD4C}" {
        }
       }
      }
     }
    }
    Action IRRU_VONBeepTypeAction {
     InputSource InputSourceSum "{672F61C86E36F488}" {
      Sources {
       InputSourceValue "{672F61C86C493BA4}" {
        FilterPreset "click"
        Input "keyboard:KC_K"
        Filter InputFilterDown "{672F61C837F10054}" {
        }
       }
       InputSourceValue "{672F61C80F375AA7}" {
        FilterPreset "click"
        Input "gamepad0:y"
        Filter InputFilterDown "{672F61C938751766}" {
        }
       }
      }
     }
    }
   }
  }
 }
}