SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{673015ECE6BDC1C1}" {
   m_sName "Enhanced Radio"
   m_sDisplayName "Enhanced Radio"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{673015ECFF37B6A1}" {
     m_sActionName "IRRU_SetFrequencyAction"
     m_sDisplayName "Set Frequency"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{673015ED48240B1B}" {
     m_sActionName "IRRU_VONRoutingAction"
     m_sDisplayName "Change Ear Routing"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{673015ED521486CC}" {
     m_sActionName "IRRU_VONBeepTypeAction"
     m_sDisplayName "Change Beep Sound"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{673167E9928C3D91}" {
     m_sActionName "IRRU_VolumeAction"
     m_sDisplayName "Change Channel Volume"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{67451A0100000010}" {
     m_sActionName "IRRU_AlternateChannelAction"
     m_sDisplayName "Set Alternate Channel"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{67451A0100000020}" {
     m_sActionName "IRRU_AlternateChannel"
     m_sDisplayName "Transmit Alternate"
     m_sPreset "hold"
    }
   }
  }
 }
}