SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6602099134F3BEAC}" {
   m_sIdentifier "Mortars"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{660209913EFE6027}" {
     m_sEntityPrefab "{45FC0FA9FE5A6C26}Prefabs/Items/Equipment/Backpacks/Backpack_US_Tripod.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{660209913A68E576}" {
       m_eItemType BACKPACK
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66020990C355D139}" {
     m_sEntityPrefab "{A464AB5D72298CFD}Prefabs/Items/Equipment/Backpacks/M252/Backpack_M252_Weapon.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66020990CDB2FC13}" {
       m_eItemType BACKPACK
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6862350BB39A233E}" {
     m_sEntityPrefab "{125D04B16155725A}Prefabs/Weapons/Launchers/M224_Bag.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6862350BBC46220B}" {
      }
     }
    }
   }
  }
 }
}