SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697E466B5032B769}" {
   m_sEntityPrefab "{F526F4C334526B74}Prefabs/Accessories/IRRU_Radio_ANPRC_LEFT_JTAC.et"
  }
  SCR_EntityCatalogInventoryItem "{697E466B5720EA7B}" {
   m_sEntityPrefab "{DFB0F41DA8D04752}Prefabs/Accessories/IRRU_Radio_ANPRC_JTAC_Right.et"
  }
  SCR_EntityCatalogInventoryItem "{698CE53003ED5D89}" {
   m_sEntityPrefab "{ED6C531BB75E8DB5}Prefabs/Accessories/IRRU_Radio_MPU5.et"
  }
  SCR_EntityCatalogInventoryItem "{697E466B5C85FE26}" {
   m_sEntityPrefab "{3AAE94CE6ADC37E6}Prefabs/Accessories/IRRU_Radio_ANPRC_V3.et"
  }
 }
}