SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68D2A0AB5428B26C}" {
   m_sIdentifier "Aircraft"
   m_aEntities {
    SCR_EntityCatalogEntry "{68D2A0AB5F98ECA1}" {
     m_sEntityPrefab "{9A1F898A7A08D8DA}Prefabs/FA18D.et"
    }
    SCR_EntityCatalogEntry "{68D2A0AB5F5CC82D}" {
     m_sEntityPrefab "{7F83C57376ED4FB1}Prefabs/FA18E.et"
    }
   }
  }
 }
}