SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{65047023F7E9E709}" {
     m_sEntityPrefab "{C837552233C303E1}Prefabs/Weapons/GrenadeLaunchers/M320_Base.et"
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
  }
  SCR_EntityCatalogMultiListEntry "{64B058B2A4EE8C6E}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{64B058B251340A0B}" {
     m_sEntityPrefab "{1526E12F183D980E}Prefabs/Weapons/MachineGuns/MK48/Mk48.et"
    }
    SCR_EntityCatalogInventoryItem "{64B058B20519F91F}" {
     m_sEntityPrefab "{D6D1BD6676214AAD}Prefabs/Weapon_Parts/Magazines/Box_762x51_MK48_100rnd_4Ball_1Tracer.et"
    }
    SCR_EntityCatalogInventoryItem "{68B84DB9F84A7A43}" {
     m_sEntityPrefab "{7983A0F9A034F6DC}Prefabs/Weapon_Parts/Magazines/Box_762x51_MK48_100rnd_4Ball_1NonTracer.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B84DB9E8A13DEC}" {
       m_eItemType MACHINE_GUN
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A50A30DFC06F326}" {
     m_sEntityPrefab "{2134E5F5A56F94CC}Prefabs/Backpanels/Accessories/506_JTAC_Antenna.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A50A30DE873C53A}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A50A3090859B5FD}" {
     m_sEntityPrefab "{A65C46E57EF489A4}Prefabs/Items/Equipment/Nightvision/PVS14/506_PVS_Thermal.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A50A3092F8CC476}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A50A30905D9DF0A}" {
     m_sEntityPrefab "{982970654D81BE80}Prefabs/Items/Equipment/Nightvision/PVS14/506_PVS_Thermal_Full.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A50A3092C51D634}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6A50A309050F1773}" {
     m_sEntityPrefab "{8B49F0AC39010080}Prefabs/Items/Equipment/Nightvision/PVS31/NVG_PVS31_WP_Full.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A50A3092D470C21}" {
       m_eItemType EQUIPMENT
      }
     }
    }
    SCR_EntityCatalogEntry "{6A50A3046C7DF08A}" {
     m_sEntityPrefab "{93DF0697D3EB6E02}Prefabs/Characters/Eyewear/Eyewear_ESS.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A50A30413604A4E}" {
       m_eItemType EQUIPMENT
      }
     }
    }
   }
  }
 }
}