SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{65047023F7E9E709}" {
     m_sEntityPrefab "{C837552233C303E1}Prefabs/Weapons/GrenadeLaunchers/M320_Base.et"
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{64B058B2A4EE8C6E}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{64B058B251340A0B}" {
     m_sEntityPrefab "{1526E12F183D980E}Prefabs/Weapons/MachineGuns/MK48/Mk48.et"
    }
    SCR_EntityCatalogInventoryItem "{64B058B20519F91F}" {
     m_sEntityPrefab "{D6D1BD6676214AAD}Prefabs/Weapon_Parts/Magazines/Box_762x51_MK48_100rnd_4Ball_1Tracer.et"
    }
    SCR_EntityCatalogInventoryItem "{68B84DB9F84A7A43}" {
     m_sEntityPrefab "{7983A0F9A034F6DC}Prefabs/Weapon_Parts/Magazines/Box_762x51_MK48_100rnd_4Ball_1NonTracer.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B84DB9E8A13DEC}" {
       m_eItemType MACHINE_GUN
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
      }
     }
    }
   }
  }
 }
}