SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68CC326A36BB970F}" {
     m_sEntityPrefab "{8697BF0D8F417BF1}Prefabs/Items/Medicine/ChestSeal/IRRU_ChestSeal.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68CC326A046010F9}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 5
      }
     }
    }
   }
  }
 }
}