SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{F8A8F80B49762902}Prefabs/Editor/EffectsModuleEntities/506th_JammerOmni500.et"
  "{37BBB9464D5DCBF0}Prefabs/Editor/EffectsModuleEntities/506th_JammerOmni1000.et"
  "{3D1EE90BFB4D3877}Prefabs/Editor/EffectsModuleEntities/506th_JammerOmni2000.et"
  "{FBF4C9D969ABB105}Prefabs/Jammer500 omnidirectional.et"
  "{155C58061C4E8FB2}Prefabs/Mega_JammerOmni500.et"
  "{F7467AB1D66C287E}Prefabs/Jammer500 directional.et"
 }
}